export const CHAT_LIST_REQUEST = 'CHAT_LIST_REQUEST'
export const CHAT_LIST_SUCCESS = 'CHAT_LIST_SUCCESS'
export const CHAT_LIST_FAIL = 'CHAT_LIST_FAIL'
export const CHAT_LIST_RESET = 'CHAT_LIST_RESET'


export const CHAT_CREATE_REQUEST = 'CHAT_CREATE_REQUEST';
export const CHAT_CREATE_SUCCESS = 'CHAT_CREATE_SUCCESS';
export const CHAT_CREATE_FAIL = 'CHAT_CREATE_FAIL';
export const CHAT_CREATE_RESET = 'CHAT_CREATE_RESET';

export const CHAT_DELETE_REQUEST = 'CHAT_DELETE_REQUEST';
export const CHAT_DELETE_SUCCESS = 'CHAT_DELETE_SUCCESS';
export const CHAT_DELETE_FAIL = 'CHAT_DELETE_FAIL';


export const MESSAGE_LIST_REQUEST = 'MESSAGE_LIST_REQUEST'
export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS'
export const MESSAGE_LIST_FAIL = 'MESSAGE_LIST_FAIL'
export const MESSAGE_LIST_RESET = 'MESSAGE_LIST_RESET'
export const ADD_MESSAGE = "ADD_MESSAGE"