export const NOTIFICATION_LIST_REQUEST = 'CHAT_LIST_REQUEST'
export const NOTIFICATION_LIST_SUCCESS = 'CHAT_LIST_SUCCESS'
export const NOTIFICATION_LIST_FAIL = 'CHAT_LIST_FAIL'
export const NOTIFICATION_LIST_RESET = 'CHAT_LIST_RESET'


// export const CHAT_CREATE_REQUEST = 'CHAT_CREATE_REQUEST';
// export const CHAT_CREATE_SUCCESS = 'CHAT_CREATE_SUCCESS';
// export const CHAT_CREATE_FAIL = 'CHAT_CREATE_FAIL';
// export const CHAT_CREATE_RESET = 'CHAT_CREATE_RESET';